apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-exam-deployment
  labels:
    app: devops-exam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-exam
  template:
    metadata:
      labels:
        app: devops-exam
    spec:
      containers:
      - name: devops-exam
        image: python:3.9
        ports:
        - containerPort: 80
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "fake-access-key"  # ערך לדוגמה
        - name: AWS_SECRET_ACCESS_KEY
          value: "fake-secret-key"  # ערך לדוגמה
        command: ["python", "-m", "http.server", "80"]