apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-exam-deployment
  labels:
    app: devops-exam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-exam
  template:
    metadata:
      labels:
        app: devops-exam
    spec:
      containers:
      - name: devops-exam
        image: jonathanmradai/exam
        ports:
        - containerPort: 5001