apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-exam-deployment
  labels:
    app: devops-exam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-exam
  template:
    metadata:
      labels:
        app: devops-exam
    spec:
      containers:
      - name: devops-exam
        image: httpd:latest  # דימוי זמני לתרגול, החלף ב-yourusername/devops-exam:latest אחר כך
        ports:
        - containerPort: 80  # httpd משתמש ב-80, נשנה ל-5001 כשיהיה לך הדימוי שלך
        env:
        - name: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY