apiVersion: v1
kind: Service
metadata:
  name: devops-exam-service
spec:
  selector:
    app: devops-exam
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80  # נשנה ל-5001 כשיהיה לך הדימוי שלך
  type: LoadBalancer