apiVersion: v1
kind: Service
metadata:
  name: devops-exam-service
spec:
  selector:
    app: devops-exam
  ports:
  - protocol: TCP
    port: 80  # the external port
    targetPort: 5001  # the internal port of the container
  type: LoadBalancer 